# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Get Python version and upgrade pip
        run: |
          python --version
          python -m pip install --upgrade pip

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.1.0"

      - name: Install project and dependencies
        # see pyproject.toml file
        run: |
          pip install .

      - name: Run tests with pytest, and generate coverage report pytest-cov
        # https://www.willprice.dev/2019/01/03/python-code-coverage.html
        run: |
          pip install pytest pytest-cov
          PYTHONPATH=src pytest -vvvv --cov=spatstat_interface --cov-report=xml
          cat ./coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
